In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("data/sessions_raw.csv")

In [23]:
df.head(10)

,user_pseudo_id,session_id,event_date,device_type,country,traffic_source,traffic_medium,event_count,pageviews,transactions,revenue,add_to_cart_events,session_start,session_end
0,1.131277e+06,6558256025,20201101,mobile,Canada,google,organic,4,1,0,NaN,0,1604258186251809,1604258194408372
1,1.202440e+06,2831108112,20201101,desktop,Canada,(direct),(none),7,2,0,NaN,0,1604208979592943,1604209020830092
2,1.202440e+06,803541518,20201101,desktop,Canada,shop.googlemerchandisestore.com,referral,3,1,0,NaN,0,1604216352814349,1604216362457383
3,1.264630e+06,407300370,20201101,desktop,Canada,(direct),(none),11,2,0,NaN,0,1604250088161864,1604250164382121
4,1.271864e+06,2218414804,20201101,mobile,India,shop.googlemerchandisestore.com,referral,3,1,0,NaN,0,1604252355306063,1604252360742752
5,1.323679e+06,7023276138,20201101,mobile,Hong Kong,(data deleted),(data deleted),4,1,0,NaN,0,1604202416502537,1604202423050321
6,1.358307e+06,3145608691,20201101,mobile,Australia,<Other>,<Other>,4,1,0,NaN,0,1604247741685420,1604247756332764
7,1.370782e+06,1108494361,20201101,desktop,India,<Other>,<Other>,5,1,0,NaN,0,1604257518132840,1604257627443136
8,1.390792e+06,7630153970,20201101,mobile,United States,shop.googlemerchandisestore.com,referral,21,6,0,NaN,0,1604247965040363,1604248044565221
9,1.511634e+06,9101062106,20201101,mobile,United States,google,organic,12,4,0,NaN,0,1604229312748361,1604229423066522

In [19]:
col_names = df.columns.tolist()
print(col_names)

col_nulls = {}

for col in df.columns:
    col_nulls[col] = df[col].isnull().sum() / len(df)

col_nulls_df = pd.DataFrame(list(col_nulls.items()), columns=['column names', 'null_percentage'])
col_nulls_df.head(20)

['user_pseudo_id', 'session_id', 'event_date', 'device_type', 'country', 'traffic_source', 'traffic_medium', 'event_count', 'pageviews', 'transactions', 'revenue', 'add_to_cart_events', 'session_start', 'session_end']

          column names  null_percentage
0       user_pseudo_id         0.000000
1           session_id         0.000000
2           event_date         0.000000
3          device_type         0.000000
4              country         0.000000
5       traffic_source         0.000000
6       traffic_medium         0.000000
7          event_count         0.000000
8            pageviews         0.000000
9         transactions         0.000000
10             revenue         0.987675
11  add_to_cart_events         0.000000
12       session_start         0.000000
13         session_end         0.000000

In [ ]:
col_datatypes = df.dtypes
col_datatype

user_pseudo_id        float64
session_id              int64
event_date              int64
device_type               str
country                   str
traffic_source            str
traffic_medium            str
event_count             int64
pageviews               int64
transactions            int64
revenue               float64
add_to_cart_events      int64
session_start           int64
session_end             int64
dtype: object

In [ ]:
df = df[df['transactions'] > 0]
df.head()

KeyError: 'transactions'